### ISSUE TITLE
Any plans to support Mac?

### ISSUE THREAD

**Issue by StephenHodgson** [LegendaryB/NeatInput#23]
Or does that come with Linux support for the most part?

**Comment by LegendaryB** [comment]
Hey @StephenHodgson,

sorry somehow github did not notify me about your question. Unfortunately the last few months I had no time to work on this library as you can see in my latest commits. 
My task regarding linux support research is still open so I can't answer this 100%. I think that the implementation could be very similiar to linux but yeah. Needs research.

Or do you maybe plan to collaborate? Would really appreciate it 👍
