### ISSUE TITLE
Bug with MouseEvent.Y

### ISSUE THREAD

**Issue by AcTiViSioN911** [LegendaryB/NeatInput#48]
Hi, I'm tracking down the movement of the mouse by subtracting the previous Y position from the current Y position, and I get the number of pixels the mouse has moved down. But when the mouse reaches the end of the screen (1440 for me), it shows strange values ​​like 1440, 1441, 1442 and 1443, which does not correspond at all to the number of pixels that the mouse passes, I can move the mouse constantly by 10 pixels, but I will only see these numbers from the list are replacing each other (everything would be fine if I constantly saw 1450, then I would simply subtract 1440). I track my mouse in an FPS game, so there is always this problem. Is there any way I can fix this?

**Comment by LegendaryB** [comment]
Hey thanks for reporting that issue. When you say always you mean also with other libraries like mine? Did this happen in one game or several games?

**Comment by LegendaryB** [comment]
Closed due missing response
