### ISSUE TITLE
Clarify that Linux is currently not supported

### ISSUE THREAD

**Issue by MindSwipe** [LegendaryB/NeatInput#49]
Right now, the about section states that NeatInput is

> A .NET standard project which aims to make keyboard and mouse input monitoring easy on Windows and Linux.

But Linux is currently not supported. I suggest we change the about section to

> A .NET standard project which aims to make keyboard and mouse input monitoring easy on Windows and eventually Linux.

To clarify that Linux support is planned, but currently not implemented

**Comment by LegendaryB** [comment]
You are right. I will update the description to make that clear. Thank you
